name: CD

on:
  push:
    tags: '*'

jobs:
  build-win:
    name: Windows Build
    runs-on: windows-2019
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        env:
          RELEASE_BUILD: 1
        run: msbuild -m -t:p2fx -p:"Configuration=Release;Platform=x86" p2fx.sln
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: p2fx-windows
          path: bin\p2fx.dll
          if-no-files-found: error
      - name: Upload PDB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: p2fx-windows-pdb
          path: bin\p2fx.pdb
          if-no-files-found: error
      - name: Upload Blender Scripts Artifact
        uses: actions/upload-artifact@v4
        with:
          name: p2fx-blender-scripts
          path: blender
          if-no-files-found: error
  release:
    name: Release
    if: github.repository == 'hero622/p2fx'
    needs: [build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Version
        id: get_release
        run: echo ::set-output name=version::${GITHUB_REF:10}
      - name: Download Windows Build
        uses: actions/download-artifact@v3
        with:
          name: p2fx-windows
      - name: Download Windows PDB
        uses: actions/download-artifact@v3
        with:
          name: p2fx-windows-pdb
      - name: Download Blender Scripts
        uses: actions/download-artifact@v3
        with:
          name: p2fx-blender-scripts
      - name: Zip Blender Scripts
        uses: montudor/action-zip@v1
        with:
            args: zip -qq -r p2fx-blender-scripts.zip p2fx
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ![CD](https://github.com/hero622/p2fx/workflows/CD/badge.svg)

            **Installation**
            - Download:
              - [Windows](https://github.com/hero622/p2fx/releases/download/${{ steps.get_release.outputs.version }}/p2fx.dll)
            - Place the binary into the game folder e.g. `Portal 2`
            - Add `+mat_hdr_level 3` to the game's launch options
            - Open developer console and enter `plugin_load p2fx`

            ---

            **Changelog**
            TODO
          files: |
            p2fx.dll
            p2fx.pdb
            p2fx-blender-scripts.zip
          prerelease: ${{ contains(github.ref, '-pre') }}
          fail_on_unmatched_files: true
